heat_template_version: 2015-10-15

description: >


####### PARAMETERS #######

parameters:
 key_name:
  type: string
  description: Pair key name

 instance_flv:
  type: string
  description: VM Flavor

 instance_img:
  type: string
  description: VM Image

 private_net_id:
  type: string
  description: Private Network ID
  default: 

 private_subnet_id:
  type: string
  description: Private Subnet ID

 public_net_id:
  type: string
  description: Public Network ID

####### PARAMETERS #######





####### RESOURCES #######

resources:

 run_script:
  type: OS::Heat::SoftwareConfig
  properties:
   group: ungrouped
   config: {get_file: assets/script.sh}

 instance_init:
  type: OS::Heat::MultipartMime
  properties:
    parts:
     - config: { get_resource: run_script }

 instance1:
  type: OS::Nova::Server
  properties:
   name: "Instance 1"
   image: { get_param: instance_img }
   flavor: { get_param: instance_flv }
   networks:
     - port: { get_resource: instance1_port0 }
   user_data_format: RAW
   user_data: { get_resource: instance_init  }

 instance1_port0:
  type: OS::Neutron::Port
  properties:
   network_id: { get_param: private_net_id }
   fixed_ips:
       - subnet_id: { get_param: private_subnet_id }

 instance1_public:
  type: OS::Neutron::FloatingIP
  properties:
   floating_network_id: { get_param: public_net_id }
   port_id: { get_resource: instance1_port0 }

####### RESOURCES #######




####### TEMPLATE OUTPUT #######

outputs:
 instance1_private_ip:
  description: IP address of instance1 in private network
  value: { get_attr: [ instance1, first_address ] }
 instance1_public_ip:
  description: Floating IP address of instance1 in public network
  value: { get_attr: [ instance1_public, floating_ip_address ] }

####### TEMPLATE OUTPUT #######
