heat_template_version: 2015-10-15

description: >

####### PARAMETERS #######

parameters:
 key_name:
  type: string
  description: Pair key name

 flavor:
  type: string
  description: VM Flavor

 image:
  type: string
  description: VM Image

 private_network_id:
  type: string
  description: Private Network ID
  default: 

 private_subnet_id:
  type: string
  description: Private Subnet ID

 public_network_id:
  type: string
  description: Public Network ID

####### RESOURCES #######

resources:

 customer_script:
  type: OS::Heat::SoftwareConfig
  properties:
   group: ungrouped
   config: {get_file: assets/script.sh}

 user_data:
  type: OS::Heat::MultipartMime
  properties:
    parts:
     - config: { get_resource: customer_script }

 instance:
  type: OS::Nova::Server
  properties:
   name: "Instance from demo heat "
   image: { get_param: image }
   flavor: { get_param: flavor }
   networks:
     - port: { get_resource: port }
   user_data_format: RAW
   user_data: { get_resource: user_data  }

 port:
  type: OS::Neutron::Port
  properties:
   network_id: { get_param: private_network_id }
   fixed_ips:
       - subnet_id: { get_param: private_subnet_id }

 floating_ip:
  type: OS::Neutron::FloatingIP
  properties:
   floating_network_id: { get_param: public_network_id }
   port_id: { get_resource: port }

####### TEMPLATE OUTPUT #######

outputs:
 instance_private_ip:
  description: IP address of instance in private network
  value: { get_attr: [ instance, first_address ] }
 instance_public_ip:
  description: Floating IP address of instance1 in public network
  value: { get_attr: [ floating_ip, floating_ip_address ] }